### ISSUE TITLE
About Mutations

### ISSUE THREAD

**Issue by Mobink980** [Computational-Intelligence-Fall18/Assignment1-Genetics#4]
Reversal mutation is the inversion mutation which is the same as reverse sequence mutation.
They both take two points, and reverse all elements between.
Swap mutation works exactly like twors mutation.

**Comment by Mobink980** [comment]
They both take two points, and reverse all elements between.

**Comment by Mobink980** [comment]
Swap mutation works exactly like twors mutation.

**Comment by Nikronic** [comment]
WTF

**Comment by Nikronic** [comment]
Reversal Mutation will be replaced with Scrumble mutation
There is no Swap mutation. Only Twors exists.

**Comment by Mobink980** [comment]
I Searched the internet and I couldn't find partial_shuffle_mutation and scramble mutation on the same page anywhere. My question is that are they both the same thing? because scramble mutation is not in the list of mutations that we should implement(https://github.com/Computational-Intelligence-Fall18/Genetics/blob/master/Assignment%201.ipynb). 
I think maybe in PSM we do the shuffle based on some probability on the whole chromosome, but in scramble mutation we choose two points, and then we shuffle between. In other words, in the PSM the genes that we shuffle are not necessarily consequent.  please help!
