### ISSUE TITLE
Scramble Mutation VS PSM

### ISSUE THREAD

**Issue by Mobink980** [Computational-Intelligence-Fall18/Assignment1-Genetics#5]
I Searched the internet and I couldn't find partial_shuffle_mutation and scramble mutation on the same page anywhere. My question is that are they both the same thing? because scramble mutation is not in the list of mutations that we should implement(https://github.com/Computational-Intelligence-Fall18/Genetics/blob/master/Assignment%201.ipynb).
I think maybe in PSM we do the shuffle based on some probability on the whole chromosome, but in scramble mutation we choose two points, and then we shuffle between. In other words, in the PSM the genes that we shuffle are not necessarily consequent. please help!

Also I have another question. I understand why we may need a chromosome which is two dimensional, but do we really need chromosomes with different lengths? I mean the problem features are not dynamic and we can work with chromosomes with a constant number of genes.
The reason that I'm asking this, is that, all the complexities aside, does it really gives us any benefit, to have solutions with different number of genes in the population?

**Comment by Mobink980** [comment]
I Searched the internet and I couldn't find partial_shuffle_mutation and scramble mutation on the same page anywhere. My question is that are they both the same thing? because scramble mutation is not in the list of mutations that we should implement(https://github.com/Computational-Intelligence-Fall18/Genetics/blob/master/Assignment%201.ipynb).
I think maybe in PSM we do the shuffle based on some probability on the whole chromosome, but in scramble mutation we choose two points, and then we shuffle between. In other words, in the PSM the genes that we shuffle are not necessarily consequent. please help!

**Comment by Mobink980** [comment]
Also I have another question. I understand why we may need a chromosome which is two dimensional, but do we really need chromosomes with different lengths? I mean the problem features are not dynamic and we can work with chromosomes with a constant number of genes.
The reason that I'm asking this, is that, all the complexities aside, does it really gives us any benefit, to have solutions with different number of genes in the population?

**Comment by Emadpourjafar** [comment]
Hi guys

**Comment by Nikronic** [comment]
First about your second question. If you solved your training and you used correct method, you should know why we need chromosomes with dynamic feature sizes.
So simply check your training answers. But if you need more info, please go to quera.ir and see questions and the answers.

**Comment by Nikronic** [comment]
And about your first question, why **partial_shuffle_mutation and scramble mutation should be on the "same page"**? What you mean about **"same page"**.
In the provided link as reference for both types of mutation, algorithms are completely clear (but your idea is right. Partial mutates whole chromosome, but Scramble mutates just  between two specific points). But in one thing you are right. I forgot to replace **scramble** with **reversal**. (we know "reversal" was duplicate).
